/*
 * Home Project Blog Service
 * Blog for the Home Project engineers 
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.softserveinc.ita.homeproject.blog.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.softserveinc.ita.homeproject.blog.client.model.Author;
import com.softserveinc.ita.homeproject.blog.client.model.Tag;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.softserveinc.ita.homeproject.blog.JSON;


/**
 * A representation of Post entity.
 */
@ApiModel(description = "A representation of Post entity.")
@JsonPropertyOrder({
  Post.JSON_PROPERTY_ID,
  Post.JSON_PROPERTY_TAGS,
  Post.JSON_PROPERTY_CREATED_ON,
  Post.JSON_PROPERTY_AUTHOR,
  Post.JSON_PROPERTY_TEXT,
  Post.JSON_PROPERTY_TITLE,
  Post.JSON_PROPERTY_PREVIEW_ATTACHMENT,
  Post.JSON_PROPERTY_UPDATED_ON
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-12T14:02:46.749850500+03:00[Europe/Helsinki]")
public class Post {
  public static final String JSON_PROPERTY_ID = "id";
  private BigDecimal id;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private List<Tag> tags = null;

  public static final String JSON_PROPERTY_CREATED_ON = "createdOn";
  private OffsetDateTime createdOn;

  public static final String JSON_PROPERTY_AUTHOR = "author";
  private Author author = null;

  public static final String JSON_PROPERTY_TEXT = "text";
  private String text;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_PREVIEW_ATTACHMENT = "previewAttachment";
  private String previewAttachment;

  public static final String JSON_PROPERTY_UPDATED_ON = "updatedOn";
  private OffsetDateTime updatedOn;


   /**
   * The ID of the Post.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the Post.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getId() {
    return id;
  }




  public Post tags(List<Tag> tags) {
    this.tags = tags;
    return this;
  }

  public Post addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * The subset of assosiated tags to the Post.
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The subset of assosiated tags to the Post.")
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Tag> getTags() {
    return tags;
  }


  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }


   /**
   * The Post creation date.
   * @return createdOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2017-07-21T17:32:28Z", value = "The Post creation date.")
  @JsonProperty(JSON_PROPERTY_CREATED_ON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }




   /**
   * The creator of the Post.
   * @return author
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The creator of the Post.")
  @JsonProperty(JSON_PROPERTY_AUTHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Author getAuthor() {
    return author;
  }




  public Post text(String text) {
    this.text = text;
    return this;
  }

   /**
   * The content of the Post.
   * @return text
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The content of the Post.")
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getText() {
    return text;
  }


  public void setText(String text) {
    this.text = text;
  }


  public Post title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The summary of the Post.
   * @return title
  **/
  @ApiModelProperty(required = true, value = "The summary of the Post.")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public Post previewAttachment(String previewAttachment) {
    this.previewAttachment = previewAttachment;
    return this;
  }

   /**
   * URL of the resource that will be used as an preview of the Post.
   * @return previewAttachment
  **/
  @ApiModelProperty(required = true, value = "URL of the resource that will be used as an preview of the Post.")
  @JsonProperty(JSON_PROPERTY_PREVIEW_ATTACHMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPreviewAttachment() {
    return previewAttachment;
  }


  public void setPreviewAttachment(String previewAttachment) {
    this.previewAttachment = previewAttachment;
  }


   /**
   * The Post update date.
   * @return updatedOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2017-07-21T17:32:28Z", value = "The Post update date.")
  @JsonProperty(JSON_PROPERTY_UPDATED_ON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedOn() {
    return updatedOn;
  }




  /**
   * Return true if this Post object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Post post = (Post) o;
    return Objects.equals(this.id, post.id) &&
        Objects.equals(this.tags, post.tags) &&
        Objects.equals(this.createdOn, post.createdOn) &&
        Objects.equals(this.author, post.author) &&
        Objects.equals(this.text, post.text) &&
        Objects.equals(this.title, post.title) &&
        Objects.equals(this.previewAttachment, post.previewAttachment) &&
        Objects.equals(this.updatedOn, post.updatedOn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tags, createdOn, author, text, title, previewAttachment, updatedOn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Post {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    previewAttachment: ").append(toIndentedString(previewAttachment)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

